/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface StudentPortal_DBQueryExecutorService_V1 {
    Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, java.sql.Date year, java.lang.String standard) throws QueryParameterMismatchException;
    Page<Object> executeSV_CountOfStudentsInAcademics(Pageable pageable, java.lang.String standard, java.sql.Date year) throws QueryParameterMismatchException;
    Page<Object> executeSV_ResultsByTestID(Pageable pageable, java.lang.String T_Name) throws QueryParameterMismatchException;
    Page<Object> executeSV_StudentAcademicResults(Pageable pageable, java.lang.Integer student_id) throws QueryParameterMismatchException;
    Page<Object> executeSV_TestDetails(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSV_TestQuery(Pageable pageable) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

