/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface School_DBQueryExecutorService_V1 {
    Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, java.lang.String year, java.lang.Integer standard) throws QueryParameterMismatchException;
    Page<Object> executeSV_CountOfStudentPerGrade(Pageable pageable, java.lang.String academicYear, java.lang.Integer standardid) throws QueryParameterMismatchException;
    Page<Object> executeSV_CountOfStudents(Pageable pageable, java.lang.Integer standard, java.lang.String year) throws QueryParameterMismatchException;
    Page<Object> executeSV_GetSTudentResultsForStandard(Pageable pageable, java.lang.String academicYear, java.lang.Integer standardid, java.lang.Integer testid) throws QueryParameterMismatchException;
    Page<Object> executeSV_Top3StudentsFromAllStandards(Pageable pageable, java.lang.Integer TESTID, java.lang.String ACADEMICYEAR) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

