/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class School_DBQueryExecutorServiceImpl_V1 implements School_DBQueryExecutorService_V1 {
	private static final Logger LOGGER = LoggerFactory.getLogger(School_DBQueryExecutorServiceImpl_V1.class);

	@Autowired
	@Qualifier("School_DBWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, java.lang.String year, java.lang.Integer standard)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("year", year);
        params.put("standard", standard);
        return queryExecutor.executeNamedQuery("SV_AcademicSubjectsByStandard", params, pageable);
	}
	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeSV_CountOfStudentPerGrade(Pageable pageable, java.lang.String academicYear, java.lang.Integer standardid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("academicYear", academicYear);
        params.put("standardid", standardid);
        return queryExecutor.executeNamedQuery("SV_CountOfStudentPerGrade", params, pageable);
	}
	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeSV_CountOfStudents(Pageable pageable, java.lang.Integer standard, java.lang.String year)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("standard", standard);
        params.put("year", year);
        return queryExecutor.executeNamedQuery("SV_CountOfStudents", params, pageable);
	}
	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeSV_GetSTudentResultsForStandard(Pageable pageable, java.lang.String academicYear, java.lang.Integer standardid, java.lang.Integer testid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("academicYear", academicYear);
        params.put("standardid", standardid);
        params.put("testid", testid);
        return queryExecutor.executeNamedQuery("SV_GetSTudentResultsForStandard", params, pageable);
	}
	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeSV_Top3StudentsFromAllStandards(Pageable pageable, java.lang.Integer TESTID, java.lang.String ACADEMICYEAR)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("TESTID", TESTID);
        params.put("ACADEMICYEAR", ACADEMICYEAR);
        return queryExecutor.executeNamedQuery("SV_Top3StudentsFromAllStandards", params, pageable);
	}

	@Transactional(value = "School_DBTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "School_DBTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

