/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Academics generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ACADEMICS`")
@IdClass(AcademicsId.class)
public class Academics implements Serializable {

    private Date academicYear;
    private String standard;
    private String classRoom;
    private String classTeacher;
    private List<AcademicSubjects> academicSubjectses = new ArrayList<>();
    private StandardDetails standardDetails;
    private List<StudentAcademics> studentAcademicses = new ArrayList<>();

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name = "`ACADEMIC_YEAR`", nullable = false)
    public Date getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(Date academicYear) {
        this.academicYear = academicYear;
    }

    @Id
    @Column(name = "`STANDARD`", nullable = false, length = 255)
    public String getStandard() {
        return this.standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    @Column(name = "`CLASS_ROOM`", nullable = true, length = 255)
    public String getClassRoom() {
        return this.classRoom;
    }

    public void setClassRoom(String classRoom) {
        this.classRoom = classRoom;
    }

    @Column(name = "`CLASS_TEACHER`", nullable = true, length = 255)
    public String getClassTeacher() {
        return this.classTeacher;
    }

    public void setClassTeacher(String classTeacher) {
        this.classTeacher = classTeacher;
    }

    
    public List<AcademicSubjects> getAcademicSubjectses() {
        return this.academicSubjectses;
    }

    public void setAcademicSubjectses(List<AcademicSubjects> academicSubjectses) {
        this.academicSubjectses = academicSubjectses;
    }

    
    
    public StandardDetails getStandardDetails() {
        return this.standardDetails;
    }

    public void setStandardDetails(StandardDetails standardDetails) {
        if(standardDetails != null) {
            this.standard = standardDetails.getStandardId();
        }

        this.standardDetails = standardDetails;
    }

    
    public List<StudentAcademics> getStudentAcademicses() {
        return this.studentAcademicses;
    }

    public void setStudentAcademicses(List<StudentAcademics> studentAcademicses) {
        this.studentAcademicses = studentAcademicses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Academics)) return false;
        final Academics academics = (Academics) o;
        return Objects.equals(getAcademicYear(), academics.getAcademicYear()) &&
                Objects.equals(getStandard(), academics.getStandard());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear(),
                getStandard());
    }
}

